### PR TITLE
Fixed typo that prevents Pet Charms from being displayed as LDB text

### PR DESCRIPTION
**Pull request by tflo**
Name of constant was not consistent throughout the project.

### CODE REVIEW

**Comment by Amadeus-** [comment]
You're absolutely correct that it was not consistent and needs to be fixed.  However, I am trying to make the name in Constants.lua match the name on wowhead.  And, sadly, Blizzard is pretty inconsistent on naming of currency ...some are singular (e.g., "Polished Pet Charm" and some are plural "Flightstones"

Therefore, the way I want to fix this is by changing how it's used in the WorldQuests.lua rather than changing the name in Constants.lua.    So, I will push a fix for this later tonight, but it will be by adjusting the other file instead of adjusting Constants.lua.

I really appreciate you doing this pull request though, it does make it clear to me what needed to be fixed.

The honest truth is that I think I had it all correct and consistent before, but I merged a pull request yesterday and I think they had it different, so that's where the inconsistency occurred.

**Comment by Amadeus-** [comment]
### 10.2.5.1
* Fixed an issue affecting Polished Pet Charms (thanks tflo for catching it.)

**Comment by tflo** [comment]
There are 3 occurrences of this constant, IIRC. If you make them all `POLISHED_PET_CHARMS` or all `POLISHED_PET_CHARM` doesn't really matter ;) … as long as they match.

**Comment by Amadeus-** [comment]
> There are 3 occurrences of this constant, IIRC. If you make them all `POLISHED_PET_CHARMS` or all `POLISHED_PET_CHARM` doesn't really matter ;) … as long as they match.

Yea, I think it should be good now.   Honestly, I think that I had it all consistent before and then one of the pull requests I merged recently caused the disconnect.

Thanks!

**Pull request closed without merging**
